version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

references:
  install_bundler: &install_bundler
    run:
      name: Install bundler
      command: gem install bundler:2.3.10
  setup: &setup
    run:
      name: Set up the environment
      command: bin/setup
  run_tests: &run_tests
    run:
      name: Run the test suite
      command: COVERAGE=true bin/rake
  run_linter: &run_linter
    run:
      name: Run the linter
      command: standardrb

jobs:
  build:
    docker:
      - image: "cimg/ruby:3.2.2-browsers"
        environment:
          PGHOST: localhost
          PGUSER: rumblr
          RAILS_ENV: test
      - image: "cimg/postgres:14.4"
        environment:
          POSTGRES_USER: rumblr
          POSTGRES_DB: rumblr_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - <<: *install_bundler
      - <<: *setup
      - <<: *run_tests
      - <<: *run_linter
