development: &default
  adapter: postgresql
  database: rumblr_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  url:  <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: rumblr_test
  host: <%= ENV.fetch('POSTGRES_HOST',  'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', nil) %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', nil) %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
